version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: circleci/node:12.19
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_PASSWORD: example
          POSTGRES_USER: example
          POSTGRES_DB: test
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - checkout
      - run: cd api && npm ci
      - run: cd api && npm test